baseURL = "https://mugenbatscha.me"
languageCode = "en-us"
title = "My Blog"
theme = "mugenbatscha"

[taxonomies]
  tag = "tags"

[author]
  name = "mugenbatscha"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#494f5c"

  homeSubtitle = "A minimal and fast theme for Hugo."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
#  [[menu.main]]
#    name = "Home"
#    pre = "home"
#    url = "/"
#    weight = 1
  [[menu.main]]
    name = "About"
    pre = ""
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4

  [[menu.social]]
    name = "twitter"
    url = "https://twitter.com/"
    pre = "twitter"
    weight = 5

  [[menu.social]]
    name = "instagram"
    url = "https://instagram.com/"
    pre = "instagram"
    weight = 6

  [[menu.social]]
    name = "github"
    url = "https://github.com/"
    pre = "github"
    weight = 7

  [[menu.social]]
    name = "twitch"
    url = "https://twitch.tv/"
    pre = "twitch"
    weight = 8